### ISSUE TITLE
Error launching the app on windows 10

### ISSUE THREAD

**Issue by gregorypilar** [OpenCobolIDE/OpenCobolIDE#279] opened 2016-01-25 19:54 UTC
HI!

I just install the new version a this error came up 

![image](https://cloud.githubusercontent.com/assets/699270/12562477/c9989032-c37b-11e5-8b0a-204e4391d26d.png)

**Comment by ColinDuquesnoy** [comment] 2016-01-25 20:10
Thank you for reporting. I can reproduce if I rename my python installation. Something is missing but I have no idea what (yet). I'll look into this asap.

**Comment by Bofinken** [comment] 2016-01-25 21:27
Looks like this issue:
https://forum.qt.io/topic/22825/solved-failed-to-load-platform-plugin

**Comment by ColinDuquesnoy** [comment] 2016-01-26 07:08
This is most probably the same issue as the one I had yesterday when building the OSX package (fixed in commit 149717f9f5d9042e0e3d2059661f80e8a135f410). I'll check that this evening when I'll get back from work. For now I have removed the windows installer from the downloads.

**Closed** 2016-01-26 17:06 UTC
Labels: Bug, Windows

**Comment by ColinDuquesnoy** [comment] 2016-01-26 17:08
Should be OK now. I've tested with a renamed python installation, works fine. The issue was actually fixed by commit 149717f9f5d9042e0e3d2059661f80e8a135f410.

I have reupload the windows installer 4.7.0 both on [launchpad](https://launchpad.net/cobcide/+download) and [github](https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7.0). Please try again and report back if you still have an issue.

**Comment by gregorypilar** [comment] 2016-01-26 17:22
its Working! 
Thank
