### ISSUE TITLE
Can't type a 'v' in Output window

### ISSUE THREAD

**Issue by royfeni** [OpenCobolIDE/OpenCobolIDE#340] opened 2016-07-04 09:08 UTC
I have searched for this issue in the forum. If it's been dealt with, it was hidden well. 

I loved OpenCobolIDE--for a while. Then I found that although the Output window would let me type stuff in in response to ACCEPT statements, I couldn't type a letter 'v', lower case or capital. Trying produced nothing, not even a blank space. Running the program in a terminal window gave no problem. So now I'm jumping back and forth from Gedit to a terminal window again, with no syntax highlighting. What's the deal with the letter 'v' anyway? Every other letter of the alphabet is fine.

**Comment by ColinDuquesnoy** [comment] 2016-07-04 09:33
Thank you for reporting! 

> What's the deal with the letter 'v' anyway? Every other letter of the alphabet is fine.

I can reproduce this issue, typing V actually paste the content of the clipboard so I think this is a wrong check of the Control modifier...

This issue is already fixed in OCIDE 4.7.4 (not released yet but will be soon) because I've spend a lot of time working on a new output window that will support most ANSI Escape Code (and it correctly handle copy/paste).

> So now I'm jumping back and forth from Gedit to a terminal window again, with no syntax highlighting.

Do you know that you can run your program in a terminal window from within OCIDE? Just go to Peferences -> Run and check "Run in external terminal".


PS: I'll close this issue once OCIDE 4.7.4 has been released so that you know it's time to update OCIDE.

**Comment by royfeni** [comment] 2016-07-04 10:38
Golly, that was quick! I love OpenCobolIDE again!

**Comment by ColinDuquesnoy** [comment] 2016-07-04 17:35
Version 4.7.4 has been [released](https://launchpad.net/cobcide/4.0/4.7.4) (packages for fedora and arch linux will come soon).

**Closed by ColinDuquesnoy** 2016-07-04 17:35 UTC
Labels: Bug
