### ISSUE TITLE
[Bug] select text

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#274] opened 2016-01-20 20:45 UTC
selecting text with the mouse seems impossible, when releasing the left mouse button the selected text is not selected any more.

## System information

- OpenCobolIDE: 4.7.0rc1
- GnuCOBOL: cobc (GNU Cobol) 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.8.0.dev0
- pyqode.cobol: 2.8.0.dev0
- pyqode.qt: 2.8.0.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

## Application log

```
INFO::open_cobol_ide::version: 4.7.dev58
INFO::open_cobol_ide::sys.stdout.encoding: cp1252
INFO::open_cobol_ide::sys.getfilesystemencoding: mbcs
INFO::open_cobol_ide::locale.getpreferredencoding: cp1252
INFO::open_cobol_ide::kernel32.GetACP: cp1252
INFO::open_cobol_ide.compilers::GnuCOBOL compiler check: success
INFO::open_cobol_ide.compilers::Executable extension: .exe
INFO::open_cobol_ide.compilers::Module extension: .dll
INFO::open_cobol_ide.app::GnuCOBOL version: GNU Cobol 1.1.0
INFO::open_cobol_ide.controllers.edit::current editor changed: G:\trunk-src_new\pgm\PROD\ARBULB\AR4000.pco
21:23:44:413::INFO::12400::open_cobol_ide::version: 4.7.0rc1
21:23:47:241::INFO::12400::open_cobol_ide.compilers::GnuCOBOL compiler check: success
21:23:47:241::INFO::12400::open_cobol_ide.compilers::Executable extension: .exe
21:23:47:242::INFO::12400::open_cobol_ide.compilers::Module extension: .dll
21:23:47:268::INFO::12400::open_cobol_ide.app::GnuCOBOL version: cobc (GNU Cobol) 1.1.0

21:23:59:478::ERROR::12400::pyqode.backend::something went bad with worker <function get_outline at 0x04A34D68>(data={'encoding': 'cp1252', 'code': '       >>SOURCE FREE\n*> This program is one example of the use of the Screen Section.\n*> tectonics: cobc -x screendemo.cbl\nidentification division.\nprogram-id. screendemo.\ndata division.\nworking-storage section.\n78  black                       value 0.\n78  blue                        value 1.\n78  green                       value 2.\n78  cyan                        value 3.\n78  red                         value 4.\n78  magenta                     value 5.\n78  yellow                      value 6.\n78  white                       value 7.\n\n01  test-record.\n    05 last-name pic x(10).\n    05 first-name pic x(10).\n    05 soc-sec-no pic x(9). \n    05 comment pic x(25).\n\n01  a-message pic x(35) value spaces.\n01  field-1-color pic 9.\n\n01 hek pic x value spaces.\n\nscreen section.\n01 blank-screen.\n   05 filler line 1 blank screen background-color white.\n\n01 entry-screen.\n    05 blank screen background-color white.\n    05 filler line 1 column 5\n        value "Enter Last Name".\n    05 screen-last-name pic x(10) using last-name\n        line 2 column 5\n        foreground-color field-1-color.\n\n    05 filler line 3 column 5\n        value "Enter First Name".\n    05 screen-first-name pic x(10) using first-name\n        line 4 column 5\n        foreground-color blue\n        HIGHLIGHT.\n\n    05 filler line 5 column 5\n        value "Enter Social Sec".\n    05 screen-soc-sec-no pic x(9) using soc-sec-no\n        line 6 column 5\n        foreground-color red\n        REVERSE-VIDEO SECURE.\n\n    05 filler line 7 column 5\n        value "Enter Comment".\n    05 screen-comment pic x(25)  using comment\n        line 8 column 5\n        foreground-color yellow\n        HIGHLIGHT.\n\n    05 screen-message pic x(80) from a-message\n        line 10 column 5\n        foreground-color white.\n\n01 exit-screen.\n   05 filler line 1 blank screen background-color yellow.\n   05 filler line 2 column 5 value "You entered:".\n   05 filler line 4 column 5 value "  Last name:".\n   05 exit-last-name pic x(10) from last-name\n       line 4 column 18.\n   05 exit-first-name pic x(10) from first-name\n       line 5 column 18.\n   05 exit-soc pic x(9) from soc-sec-no\n       line 6 column 18.\n   05 exit-comment pic x(25) from comment\n       line 7 column 18.\n   05 filler line 24 column 1 value "hit enter".\n   05 exit-hek pic x using hek line 24 column 40.\n       \nprocedure division.\n    display blank-screen.\n    move magenta to field-1-color.\n\nscreen-loop.\n    display entry-screen.\n    accept entry-screen.\n    if last-name(1:1) not equal "q"\n        move green  to field-1-color\n        move "Last name must begin with q to exit" to a-message\n        display entry-screen\n        go to screen-loop \n    end-if.\n\n    display exit-screen.\n    accept exit-screen.\n\n    stop run.\n', 'path': 'G:\\oc_proj\\compile_test\\screendemo.cbl'})
21:23:59:478::ERROR::12400::pyqode.backend::Traceback (most recent call last):
21:23:59:479::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.core\pyqode\core\backend\server.py", line 136, in _handle
21:23:59:479::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\backend\workers.py", line 73, in get_outline
21:23:59:479::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 309, in defined_names
21:23:59:479::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 170, in parse_section
21:23:59:479::ERROR::12400::pyqode.backend::AttributeError: 'NoneType' object has no attribute 'add_child'
21:23:59:552::ERROR::12400::pyqode.backend::something went bad with worker <function get_outline at 0x04A34D68>(data={'encoding': 'cp1252', 'code': '       >>SOURCE FREE\n*> This program is one example of the use of the Screen Section.\n*> tectonics: cobc -x screendemo.cbl\nidentification division.\nprogram-id. screendemo.\ndata division.\nworking-storage section.\n78  black                       value 0.\n78  blue                        value 1.\n78  green                       value 2.\n78  cyan                        value 3.\n78  red                         value 4.\n78  magenta                     value 5.\n78  yellow                      value 6.\n78  white                       value 7.\n\n01  test-record.\n    05 last-name pic x(10).\n    05 first-name pic x(10).\n    05 soc-sec-no pic x(9). \n    05 comment pic x(25).\n\n01  a-message pic x(35) value spaces.\n01  field-1-color pic 9.\n\n01 hek pic x value spaces.\n\nscreen section.\n01 blank-screen.\n   05 filler line 1 blank screen background-color white.\n\n01 entry-screen.\n    05 blank screen background-color white.\n    05 filler line 1 column 5\n        value "Enter Last Name".\n    05 screen-last-name pic x(10) using last-name\n        line 2 column 5\n        foreground-color field-1-color.\n\n    05 filler line 3 column 5\n        value "Enter First Name".\n    05 screen-first-name pic x(10) using first-name\n        line 4 column 5\n        foreground-color blue\n        HIGHLIGHT.\n\n    05 filler line 5 column 5\n        value "Enter Social Sec".\n    05 screen-soc-sec-no pic x(9) using soc-sec-no\n        line 6 column 5\n        foreground-color red\n        REVERSE-VIDEO SECURE.\n\n    05 filler line 7 column 5\n        value "Enter Comment".\n    05 screen-comment pic x(25)  using comment\n        line 8 column 5\n        foreground-color yellow\n        HIGHLIGHT.\n\n    05 screen-message pic x(80) from a-message\n        line 10 column 5\n        foreground-color white.\n\n01 exit-screen.\n   05 filler line 1 blank screen background-color yellow.\n   05 filler line 2 column 5 value "You entered:".\n   05 filler line 4 column 5 value "  Last name:".\n   05 exit-last-name pic x(10) from last-name\n       line 4 column 18.\n   05 exit-first-name pic x(10) from first-name\n       line 5 column 18.\n   05 exit-soc pic x(9) from soc-sec-no\n       line 6 column 18.\n   05 exit-comment pic x(25) from comment\n       line 7 column 18.\n   05 filler line 24 column 1 value "hit enter".\n   05 exit-hek pic x using hek line 24 column 40.\n       \nprocedure division.\n    display blank-screen.\n    move magenta to field-1-color.\n\nscreen-loop.\n    display entry-screen.\n    accept entry-screen.\n    if last-name(1:1) not equal "q"\n        move green  to field-1-color\n        move "Last name must begin with q to exit" to a-message\n        display entry-screen\n        go to screen-loop \n    end-if.\n\n    display exit-screen.\n    accept exit-screen.\n\n    stop run.\n', 'path': 'G:\\oc_proj\\compile_test\\screendemo.cbl'})
21:23:59:553::ERROR::12400::pyqode.backend::Traceback (most recent call last):
21:23:59:553::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.core\pyqode\core\backend\server.py", line 136, in _handle
21:23:59:553::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\backend\workers.py", line 73, in get_outline
21:23:59:553::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 309, in defined_names
21:23:59:553::ERROR::12400::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 170, in parse_section
21:23:59:553::ERROR::12400::pyqode.backend::AttributeError: 'NoneType' object has no attribute 'add_child'
21:24:07:273::INFO::12400::open_cobol_ide.controllers.cobol::running compilation thread: ['G:\\oc_proj\\compile_test\\screendemo.cbl']
21:24:07:274::INFO::12400::open_cobol_ide.compilers::compiling G:\oc_proj\compile_test\screendemo.cbl
21:24:07:275::INFO::12400::open_cobol_ide.compilers::compilation skipped, up to date...
21:24:07:281::INFO::12400::open_cobol_ide.controllers.cobol::running program
21:25:13:039::INFO::12400::open_cobol_ide.controllers.cobol::running compilation thread: ['G:\\oc_proj\\compile_test\\CALC-WEEKDAY.cbl']
21:25:13:040::INFO::12400::open_cobol_ide.compilers::compiling G:\oc_proj\compile_test\CALC-WEEKDAY.cbl
21:25:13:041::INFO::12400::open_cobol_ide.compilers::compilation skipped, up to date...
21:25:13:046::INFO::12400::open_cobol_ide.controllers.cobol::running program
21:27:09:325::INFO::12400::open_cobol_ide.controllers.cobol::running compilation thread: ['G:\\oc_proj\\compile_test\\CALC-WEEKDAY.cbl']
21:27:09:326::INFO::12400::open_cobol_ide.compilers::compiling G:\oc_proj\compile_test\CALC-WEEKDAY.cbl
21:27:09:327::INFO::12400::open_cobol_ide.compilers::compilation skipped, up to date...
21:27:09:332::INFO::12400::open_cobol_ide.controllers.cobol::running program
21:28:48:998::INFO::12400::open_cobol_ide.controllers.cobol::running compilation thread: ['G:\\oc_proj\\compile_test\\CALC-WEEKDAY.cbl']
21:28:48:999::INFO::12400::open_cobol_ide.compilers::compiling G:\oc_proj\compile_test\CALC-WEEKDAY.cbl
21:28:48:999::INFO::12400::open_cobol_ide.compilers::compilation skipped, up to date...
21:28:49:004::INFO::12400::open_cobol_ide.controllers.cobol::running program
21:29:58:574::INFO::12400::open_cobol_ide.controllers.cobol::running compilation thread: ['G:\\oc_proj\\compile_test\\CALC-WEEKDAY.cbl']
21:29:58:575::INFO::12400::open_cobol_ide.compilers::compiling G:\oc_proj\compile_test\CALC-WEEKDAY.cbl
21:29:58:905::INFO::12400::open_cobol_ide.compilers::binary file 'G:\\oc_proj\\compile_test\\bin\\CALC-WEEKDAY.exe' created:  True
21:29:58:905::INFO::12400::open_cobol_ide.compilers::compile results: 0 - []
21:29:58:910::INFO::12400::open_cobol_ide.controllers.cobol::running program

```

**Comment by ColinDuquesnoy** [comment] 2016-01-20 21:05
I can't reproduce (tested on Windows 10, OSX and Linux). 

Does it happen with every file? What if you close and reopen the IDE?

**Comment by Bofinken** [comment] 2016-01-21 11:05
Yesterday it was 100% of the time with that file, tested today with
different files and it seems that it worked in about 50% of the tests, very
hard to select with the left button key. Just using the keyboard was no
problem.

Win 10 with a Microsoft mouse.

 

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 20 januari 2016 22:05
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] [Bug] select text (#274)

 

I can't reproduce (tested on Windows 10, OSX and Linux). 

Does it happen with every file? What if you close and reopen the IDE?


Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/274#issuecomment-173358
522>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmHVZi4dCK7oGsU81wOG_R0LM5AlJks5
pb-4JgaJpZM4HI9nL.gif>

**Comment by ColinDuquesnoy** [comment] 2016-01-21 12:11
Weird... This sounds like a hardware issue to me.

- Have you tried with another application such as Notepad ++ or Sublime text?
- Have you tried with another mouse?
- If this is a laptop, have you tried to disable the trackpad?
- If this does not happen in other apps, have you tried to install the previous preview version?
- Have you tried to restore factory defaults? (you might want to export your preferences before doing so (File -> Export preferences)).

@GitMensch @axtens Can you reproduce it on Windows with v4.7RC1 ?

**Comment by Bofinken** [comment] 2016-01-21 13:56
Yes, worked fine with Notepad ++, but I tested the same on my laptop and had
no problem.
Reinstalled the mouse-driver on my stationary PC and found no problem.
Seems like it was a driver problem that did not surface in any other
application.

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 21 januari 2016 13:11
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] [Bug] select text (#274)

 

Weird... This sounds like a hardware issue to me.

*	Have you tried with another application such as Notepad ++ or
Sublime text?
*	Have you tried with another mouse?
*	If this is a laptop, have you tried to disable the trackpad?
*	If this does not happen in other apps, have you tried to install the
previous preview version?
*	Have you tried to restore factory defaults? (you might want to
export your preferences before doing so (File -> Export preferences)).

@GitMensch <https://github.com/GitMensch>  @axtens
<https://github.com/axtens>  Can you reproduce it on Windows with v4.7RC1 ?


Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/274#issuecomment-173552
923>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmFm4zqbo8HFPR1GIQ8uFJNlfyEQNks5
pcMJXgaJpZM4HI9nL.gif>

**Comment by ColinDuquesnoy** [comment] 2016-01-21 14:20
Ok, maybe a quirk of Qt 5.5 which does not fully support Win 10 (full support is planned for Qt 5.6 which should be released next month).

Closing as "not our bug"...

**Closed by ColinDuquesnoy** 2016-01-21 14:20 UTC
Labels: Bug, Cannot reproduce, Not our bug
