### ISSUE TITLE
[Bug] cannot find module

### ISSUE THREAD

**Issue by mflaim1** [OpenCobolIDE/OpenCobolIDE#244] opened 2015-10-29 20:21 UTC
I am not sure if this is a bug or not, but I am trying to call a subroutine and it cannot find the module I want to call

## System information

- OpenCobolIDE: 4.6.5
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (64bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment] 2015-10-29 22:06
Hello,

Thank you for reporting. 

I don't know if this is a bug, running submodules works for me. I'll need a bit more information:

* What OS? Which release are you using? Downloaded from where? (I see the version you have are a bit funky since they mix an old release of ocide with a brand new development version of pyQode).
* Is the module in the same directory as your main executable? Can you show the code where you call your submodule and the complete compiler output?

**Comment by mflaim1** [comment] 2015-10-29 23:37
Thank you so much for emailing back to fast! I am new to COBOL so it totally may be me not knowing what I am doing. I am using a Mac, using OpenCobolIde 4.6.5. The files are both in the same directory.

this is my MAIN:
IDENTIFICATION DIVISION.
PROGRAM-ID. MAIN.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STUDENT-ID PIC 9(4) VALUE 1000.
01 WS-STUDENT-NAME PIC A(15) VALUE 'Tim'.

PROCEDURE DIVISION.
CALL 'UTIL' USING WS-STUDENT-ID, WS-STUDENT-NAME.
DISPLAY 'Student Id : ' WS-STUDENT-ID
DISPLAY 'Student Name : ' WS-STUDENT-NAME
STOP RUN.

and this is the subroutine:

IDENTIFICATION DIVISION.
PROGRAM-ID. UTIL.

DATA DIVISION.
LINKAGE SECTION.
01 LS-STUDENT-ID PIC 9(4).
01 LS-STUDENT-NAME PIC A(15).

PROCEDURE DIVISION USING LS-STUDENT-ID, LS-STUDENT-NAME.
DISPLAY 'In Called Program'.
MOVE 1111 TO LS-STUDENT-ID.
EXIT PROGRAM.

and the compiler is giving this back:

MAIN.cbl:16: libcob: Cannot find module ‘UTIL'

On Oct 29, 2015, at 6:06 PM, Colin Duquesnoy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Thank you for reporting.

I don't know if this is a bug, running submodules works for me. I'll need a bit more information:

  *   What OS? Which release are you using? Downloaded from where? (I see the version you have are a bit funky since they mix an old release of ocide with a brand new development version of pyQode).
  *   Is the module in the same directory as your main executable? Can you show the code where you call your submodule and the complete compiler output?

**Comment by ColinDuquesnoy** [comment] 2015-10-30 07:59
Hello, I think it might be a bug on OSX. I've tried your code on Linux, 
it works as expected. I'll try it on my mac during the weekend.

**Comment by ColinDuquesnoy** [comment] 2015-11-01 10:35
I can reproduce it on my mac. But it also happen when I run when the program from the command line:

```
Colins-MacBook-Pro:~ Colin$ cd bin
Colins-MacBook-Pro:bin Colin$ ./main 
main.cob:10: libcob: Cannot find module 'UTIL'
Colins-MacBook-Pro:bin Colin$ ls
UTIL.so	main
Colins-MacBook-Pro:bin Colin$ 
```

There is probably an environment variable to set to make it work but I don't know which one. I am using GnuCobol 1.1.0 installed with homebrew (``brew gnu-cobol``)

Compiler information:

```
Colins-MacBook-Pro:bin Colin$ cobc --version
cobc (GNU Cobol) 1.1.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     Oct 31 2015 19:12:35
Packaged  Jan 20 2014 07:40:53 UTC
C version "5.2.0"
Colins-MacBook-Pro:bin Colin$ cobc --info
cobc (GNU Cobol) 1.1.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     Oct 31 2015 19:12:35
Packaged  Jan 20 2014 07:40:53 UTC
C version "5.2.0"
Build information
Build environment        : i386-apple-darwin15.0.0
CC                       : gcc-5
CPPFLAGS                 : -I/usr/local/opt/gmp/include
                           -I/usr/local/opt/berkeley-db4/include
CFLAGS                   : -O2
LD                       : ld
LDFLAGS                  : -L/usr/local/opt/gmp/lib
                           -L/usr/local/opt/berkeley-db4/lib

GNU Cobol information
COB_CC                   : gcc-5
COB_CFLAGS               : -I/usr/local/Cellar/gnu-cobol/1.1_1/include
                           -I/usr/local/opt/gmp/include
                           -I/usr/local/opt/berkeley-db4/include
COB_LDFLAGS              : -L/usr/local/opt/gmp/lib
                           -L/usr/local/opt/berkeley-db4/lib
COB_LIBS                 : -L/usr/local/opt/gmp/lib
                           -L/usr/local/opt/berkeley-db4/lib
                           -L/usr/local/Cellar/gnu-cobol/1.1_1/lib -lcob
                           -lm -lgmp -lncurses -ldb
COB_CONFIG_DIR           : /usr/local/Cellar/gnu-cobol/1.1_1/share/gnu-cobol/config
COB_COPY_DIR             : /usr/local/Cellar/gnu-cobol/1.1_1/share/gnu-cobol/copy
COB_LIBRARY_PATH         : /usr/local/Cellar/gnu-cobol/1.1_1/lib/gnu-cobol
COB_MODULE_EXT           : dylib
COB_EXEEXT               : 
Dynamic loading          : System
"CBL_" param check       : Disabled
Variable format          : 0
BINARY-C-LONG            : 8 bytes
Sequential handler       : Internal
ISAM handler             : BDB
Colins-MacBook-Pro:bin Colin$ cobcrun --version
cobcrun (GNU Cobol) 1.1.0
Copyright (C) 2004-2009 Roger While
Built    Oct 31 2015 19:12:39
Packaged Jan 20 2014 07:40:53 UTC
Colins-MacBook-Pro:bin Colin$ cobcrun --runtime-env
cobcrun: unrecognized option `--runtime-env'
```

Maybe @GitMensch has an idea?

**Comment by GitMensch** [comment] 2015-11-01 12:03
As this is no bug of OCIDE but a problem with the installation of GnuCOBOL I'd suggest to close this and remove the bug tag.
This problem is likely faster solved if posted at https://sourceforge.net/p/open-cobol/discussion/help/ - as a starter I'd set ``COB_LIBRARY_PATH=.`` or better ``COB_LIBRARY_PATH=/path/to/where/your/module/is``. In any case - is installing GnuCOBOL 2.0 an option? This has some better options for debugging issues...
Does it work if compiled on the command line?

**Comment by ColinDuquesnoy** [comment] 2015-11-01 12:51
For reference, I've tried GnuCobol 2 (one can easily install it with ``brew install gnu-cobol --devel``) but I get the same results:

```
Colins-MacBook-Pro:~ Colin$ /usr/local/bin/cobc -x -o main -std=default -debug -free main.cob
Colins-MacBook-Pro:~ Colin$ /usr/local/bin/cobc -o UTIL.so -std=default -debug -free UTIL.cbl
./main 
main.cob: 10: libcob: Cannot find module 'UTIL'
Colins-MacBook-Pro:~ Colin$ ls
Desktop		Library		Pictures	UTIL.cbl	main.cob
Documents	Movies		Public		UTIL.so
Downloads	Music		Qt		main
Colins-MacBook-Pro:~ Colin$ pwd
/Users/Colin
Colins-MacBook-Pro:~ Colin$ export COB_LIBRARY_PATH=/Users/Colin/
Colins-MacBook-Pro:~ Colin$ echo $COB_LIBRARY_PATH 
/Users/Colin/
Colins-MacBook-Pro:~ Colin$ ./main 
main.cob: 10: libcob: Cannot find module 'UTIL'
```

Here is some output trying to run the submodule with cobcrun:

```
Colins-MacBook-Pro:~ Colin$ cobcrun UTIL
libcob: Cannot find module 'UTIL'
Colins-MacBook-Pro:~ Colin$ cobcrun UTIL.so
libcob: Cannot find module 'UTIL.so'
Colins-MacBook-Pro:~ Colin$ cobcrun --runtime-env
GNU Cobol runtime environment

All values were resolved from current environment. 

Call environment
    COB_LIBRARY_PATH             : /Users/Colin/
        resolve_path             : /Users/Colin/:.:/usr/local/Cellar/gnu-cobol/2.0_nightly_r411_1/lib/gnu-cobol
    COB_PRE_LOAD                 : not set
        base_preload_ptr         : not set
    COB_LOAD_CASE                : not set
        name_convert             : No (default)
    COB_PHYSICAL_CANCEL          : not set
        physical_cancel          : No (default)


File I/O
    COB_SYNC                     : not set
        cob_do_sync              : No (default)
    COB_LS_USES_CR               : not set
        cob_ls_uses_cr           : No (default)
    COB_SORT_MEMORY              : not set
        cob_sort_memory          : 128.00 MB (default)
    COB_SORT_CHUNK               : not set
        cob_sort_chunk           : 256.00 kB (default)
    COB_FILE_PATH                : not set
        cob_file_path            : not set
    COB_LS_NULLS                 : not set
        cob_ls_nulls             : No (default)
    COB_LS_FIXED                 : not set
        cob_ls_fixed             : No (default)
    COB_VARSEQ_FORMAT            : 0 (default), [2-byte record-length] [0000]
                                   [record-data]
        cob_varseq_type          : 0 (default), [2-byte record-length] [0000]
                                   [record-data] (default)
    COB_UNIX_LF                  : not set
        cob_unix_lf              : No (default)


Screen I/O
    COB_REDIRECT_DISPLAY         : not set
        cob_disp_to_stderr       : No (default)
    COB_BELL                     : not set
        cob_beep_value           : 0 (default)
    COB_TIMEOUT_SCALE            : not set
        cob_timeout_scale        : 1000 (default)
    COB_SCREEN_EXCEPTIONS        : not set
        cob_extended_status      : No (default)
    COB_SCREEN_ESC               : not set
        cob_screen_esc           : No (default)
    COB_LEGACY                   : not set
        cob_legacy               : No (default)


Miscellaneous
    COB_SET_TRACE                : not set
        cob_line_trace           : No (default)
    COB_TRACE_FILE               : not set
        cob_trace_file           : stderr (default)
    COB_DISABLE_WARNINGS         : not set
        cob_display_warn         : 1
    COB_ENV_MANGLE               : not set
        cob_env_mangle           : No (default)
Colins-MacBook-Pro:~ Colin$ cobcrun ./UTIL
libcob: Cannot find module 'UTIL'
Colins-MacBook-Pro:~ Colin$ cobcrun ./UTIL.so
libcob: Cannot find module 'UTIL.so'
Colins-MacBook-Pro:~ Colin$ cobcrun /Users/Colin/UTIL
libcob: Cannot find module 'UTIL'
Colins-MacBook-Pro:~ Colin$ cobcrun /Users/Colin/UTIL.so
libcob: Cannot find module 'UTIL.so'
```

**Comment by GitMensch** [comment] 2015-11-01 13:13
Thank you for the reference. Just to let you know: only recent cobcrun will take a path (they prefix the path to COB_LIBRARY_PATH) and you only use the name without extension (therefore ``cobcrun ./UTIL`` and ``cobcrun /Users/Colin/UTIL`` are valid [with GC 2.x] and with every version ``cobcrun UTIL``).
Please run compiler with ``cobc -free -g -debug -v UTIL.cbl`` and post compiler output here, together with the generated source files attached.

Or even better: directly create a bug ticket at https://sourceforge.net/p/open-cobol/bugs/ with the information from this issue summarized, adding the information "happens with both GC 1.1 and GC 2.0 nightly r411". I'll investigate this and report back here for reference when finished.

Simon

BTW @ColinDuquesnoy Would be the first issue you create for GC, wouldn't it ;-)
Just because I've never had a Mac to test with: does something like ``brew install gnu-cobol --devel --test`` exists?

**Comment by ColinDuquesnoy** [comment] 2015-11-01 13:43
Here is the output:

```
Colins-MacBook-Pro:~ Colin$ cobc -free -g -debug -v UTIL.cbl
Command line:	cobc -free -g -debug -v UTIL.cbl 
Preprocessing:	UTIL.cbl -> UTIL.i
Return status:	0
Parsing:	UTIL.i (UTIL.cbl)
Return status:	0
Translating:	UTIL.i -> UTIL.c (UTIL.cbl)
Executing:	clang -I/usr/local/Cellar/gnu-cobol/2.0_nightly_r411_1/include
		-I/usr/local/opt/gmp/include
		-I/usr/local/opt/berkeley-db4/include -pipe -Wno-unused
		-fsigned-char -Wno-pointer-sign -g -bundle -flat_namespace
		-undefined suppress -fno-common -DPIC -o "UTIL.dylib" "UTIL.c"
		-L/usr/local/opt/gmp/lib -L/usr/local/opt/berkeley-db4/lib
		-L/usr/local/opt/gmp/lib -L/usr/local/opt/berkeley-db4/lib
		-L/usr/local/Cellar/gnu-cobol/2.0_nightly_r411_1/lib -lcob -lm
		-lgmp -lncurses -ldb
Return status:	0
```

@GitMensch  I am going to create my first bug report for GC ;-)

> Just because I've never had a Mac to test with: does something like brew install gnu-cobol --devel --test exists?

Reading the [homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gnu-cobol.rb), I don't think that exists but it might be a nice addition.

**Comment by ColinDuquesnoy** [comment] 2015-11-01 16:07
Reopening because the bug actually come from OCIDE.

This happens because I use the -o option. By getting rid of that option, the correct extension will be used automatically and that will solve your problem.

**Comment by GitMensch** [comment] 2015-11-01 16:48
The fix may not work depending on the actual Mac version used and how the package gnu-cobol was configured. ``cobc`` does always do what the system (at least ``cobcrun``) expects, therefore I suggest to drop ``-o`` for normal configurations (both module and executable).

**Comment by ColinDuquesnoy** [comment] 2015-11-01 16:53
Then how can I honore the output build directory. Consider the following command (where the current working directory is set to the one of the source file to compiler:

```
cobc -x -o build/main.exe -debug main.cbl
```

If I use:

```
cobc -x -debug main.cbl
```

main.exe will be create next to the source file.

I can set the working directory to ``$source_file_path/build`` and use the full path to source file but that will cause problems if the source file has spaces in its path and the user is using a MinGW based compiler.

How does cobc knows about the right extension?

**Comment by mflaim1** [comment] 2015-11-01 17:14
I am sorry, I am not following. You found a solution?

On Nov 1, 2015, at 11:53 AM, Colin Duquesnoy <notifications@github.com<mailto:notifications@github.com>> wrote:


Then how can I honore the output build directory. Consider the following command (where the current working directory is set to the one of the source file to compiler:

cobc -x -o build/main.exe -debug main.cbl


If I use:

cobc -x -debug main.cbl


main.exe will be create next to the source file.

I can set the working directory to $source_file_path/build and use the full path to source file but that will cause problems if the source file has spaces in its path and the user is using a MinGW based compiler.

How does cobc knows about the right extension?

**Comment by ColinDuquesnoy** [comment] 2015-11-01 17:15
@mflaim1 Yes but it might not work on every configuration so I am reopening.

**Comment by mflaim1** [comment] 2015-11-01 17:18
Oh ok, what is the exact solution? Can I try it on my computer now?
On Nov 1, 2015, at 12:15 PM, Colin Duquesnoy <notifications@github.com<mailto:notifications@github.com>> wrote:


@mflaim1<https://github.com/mflaim1> Yes but it might not work on every configuration so I am reopening.

**Comment by ColinDuquesnoy** [comment] 2015-11-01 17:25
The issue is the extension used when the IDE compile your subroutine. Depending on how cobc was built and configured, it may expect a .so extension or a .dylib. 

You can recompile your two files using the following command (assuming your files are named MAIN.cbl and UTIL.cbl):

```
cobc -x -debug -free MAIN.cbl
cobc -debug -free UTIL.cbl
```

**Comment by ColinDuquesnoy** [comment] 2015-11-01 18:02
@GitMensch  

There are many reasons why I would like to keep control on the compiler output. Off the top of my head I can see the following reasons:

  - I need to know the full output path even before running the compiler, for checking modification time and avoid needless compilation
  - I need to be able to specify a build directory (this is especially important for #227)
  - I also need it to implement the clean action

So I think there is no way I will drop the -o option. 

I can determine the right extension by running ``cobc --info`` and by looking at ``COB_MODULE_EXT`` and ``COB_EXEXT`` but I don't like this solution as it is not supported by old compilers and those old compiler are still lurking arround in many popular and stable GNU/Linux distributions (e.g. ubuntu still provides OpenCOBOL 1.1 from many years ago).

So the idea I have in mind at the moment is to simply add two more options to the compiler preferences:
  - executable extension: would default to ".exe" on windows and "" anywhere else
  - module extension: would default to ".dll" on windows, ".so" on GNU/Linux and ".dylib" on OSX

Thoughts?

**Comment by GitMensch** [comment] 2015-11-01 18:12
@ColinDuquesnoy You indeed have good reasons for keeping the output parameter.

If you don't want to read ``COB_EXEEXT`` and ``COB_MODULEEXT`` (inserted to defaults.h with lots of checks and settings for getting the correct compiler and its settings) you have two options:

1. the way configure does it - but much less complicated: extend your existing compiler check - check what extension it has produced after successful compilation *or*
2. add a setting and default to the reasonable values you've suggested

It's your decision - I'd use the first approach.
Simon

**Comment by ColinDuquesnoy** [comment] 2015-11-01 19:11
@GitMensch  I went with the first approach.

@mflaim1 You can test it by installing the latest preview build available here: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview3

**Closed by ColinDuquesnoy** 2015-11-01 19:11 UTC
Labels: Bug, Mac OSX

**Comment by mflaim1** [comment] 2015-11-01 19:37
Okay great! Thank you so much for all your help!
On Nov 1, 2015, at 2:11 PM, Colin Duquesnoy <notifications@github.com<mailto:notifications@github.com>> wrote:


@GitMensch<https://github.com/GitMensch> I went with the first approach.

@mflaim1<https://github.com/mflaim1> You can test it by installing the latest preview build available here: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview3
