### ISSUE TITLE
Navigation tree auto-uncollapses

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#314] opened 2016-04-15 09:13 UTC
### Description

Steps to reproduce:
- open a source file
- open navigation pane if necessary
- collapse working-storace
- write code

result: all entries are uncollapsed again (even if navigation pane is "locked")
### System information
- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: cobc (GNU Cobol) 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

BTW: Seems like this either only happens on "big" source files or with source files where the missing header entries are assumed.

**Comment by ColinDuquesnoy** [comment] 2016-04-15 09:34
I can't reproduce this. I quickly see collapsed node being uncollapsed then recollapsed. I am aware of that small issue but never found a solution (never really looked hard neither). I'll leave this issue for pyqode 3.0 (will be in a future version of OCIDE).

**Comment by GitMensch** [comment] 2016-04-15 10:25
OK.

**Comment by GitMensch** [comment] 2016-04-21 07:09
Found it. Some more detailed steps:

* open a complete source file
* open navigation pane if necessary
* collapse working-storage in navigation panel

Result: Working storage is collapsed in code panel, too. (One can argue if this is what the programmer wants [especially if the navigation panel is locked], but it looks like a feature-by-design).

Now doing the same again with a file which is NOT complete (working-storage assumed):

I think I know what happened:

* open a source file without headers ("starting" with a variable definition)
* open navigation pane if necessary
* collapse working-storage in navigation panel (as there is no working-storage in the code it cannot be collapsed in code view)
* click somewhere in the code panel (variable definitions)

Result: Navigation panel unfolds working-storage "as the cursor is in there" --> likely not intended (neither by the user not by you)


And the last one which was the initial issue:

* open a source file without headers ("starting" with a variable definition)
* open navigation pane if necessary
* collapse working-storage in navigation panel (as there is no working-storage in the code it cannot be collapsed in code view)
* click somewhere in the code panel (somewhere in the procedure division) --> nothing happens with navigation panel as we're in the procedure division which is already completely unfolded --> fine
* press any key (= change something in the code pane, either directly or via paste/cut)

Result: Navigation panel unfolds working-storage definitely not intended


This lead to another observation:

* open a complete source file
* open navigation pane if necessary
* collapse a sub-item in working-storage in navigation panel
* collapse working-storage in navigation panel
* un-collapse working-storage in navigation panel

Result: the sub-item in working-storage is still collapsed --> fine

Now with assumed headers:

* open a source file without headers ("starting" with a variable definition)
* open navigation pane if necessary
* collapse a sub-item in working-storage in navigation panel
* collapse working-storage in navigation panel
* un-collapse working-storage in navigation panel

Result: Every sub-item of working-storage in navigation panel is unfolded


My suggestion is to don't unfold anything in the navigation pane "automatically" if navigation pane is locked [this should give a possible workaround for the bug part, too], if possible: please provide this in OCIDE 4.7.3.

Not sure how hard it is possible to fix the bug in navigation panel with assumed headers. Does this have to wait for pycode 3.0?

**Comment by ColinDuquesnoy** [comment] 2016-04-21 07:31
Interesting. Yes it will need to wait pyqode 3.0.

**Comment by GitMensch** [comment] 2016-04-21 08:59
What about the following part

> My suggestion is to don't unfold anything in the navigation pane "automatically" if navigation pane is locked [this should give a possible workaround for the bug part, too], if possible: please provide this in OCIDE 4.7.3.

**Comment by ColinDuquesnoy** [comment] 2016-04-21 09:01
> My suggestion is to don't unfold anything in the navigation pane "automatically" if navigation pane is locked [this should give a possible workaround for the bug part, too], if possible: please provide this in OCIDE 4.7.3.

It does not unfold anything, it clears the entire tree and (re)add each nodes. It uses code folding to determine if the node was folded or not. Changing this needs some time and requires some testing. Not a candidate for the today's release.

**Comment by GitMensch** [comment] 2016-04-21 10:03
Thank you for the answer. I'm really looking forward to the release.
BTW: I'd bump the version that uses pycode 3 to OCIDE 4.8 (and assume HE will be the next target after OCIDE 4.7.3)

**Comment by ColinDuquesnoy** [comment] 2016-04-21 10:07
>  I'd bump the version that uses pycode 3 to OCIDE 4.8 (and assume HE will be the next target after OCIDE 4.7.3)

Makes sense.

**Closed** 2016-11-11 12:11 UTC
Labels: Bug, pyqode, wontfix
