### ISSUE TITLE
[Unhandled exception] AttributeError

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#382] opened 2016-12-09 14:43 UTC
### Description

...

### Traceback

```
  File "d:\documents\pyqode.core\pyqode\core\modes\filewatcher.py", line 189, in _check_for_pending
  File "d:\documents\pyqode.core\pyqode\core\modes\filewatcher.py", line 149, in _notify

AttributeError: 'NoneType' object has no attribute 'save_on_focus_out'
```

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.4
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.0.2
- QDarkStyle: 2.1

Application log: https://gist.github.com/3117caccdb3b1a7121ac6608e54836f3

**Comment by ColinDuquesnoy** [comment] 2016-12-09 16:44
Duplicate of #354

**Closed by ColinDuquesnoy** 2016-12-09 16:44 UTC
