### ISSUE TITLE
[Bug] Opened dock widgets are not restored

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#130] opened 2015-05-25 12:02 UTC
May be an Enhancement request, but it's a little bit disturbing that the dock widgets are always restored to the default on restart of OCIDE.

## System information

- OpenCobolIDE: 4.6.0.dev0
- GnuCOBOL: None
- Python: 3.4.3 (64bits)
- Qt: 4.8.6
- PyQt: 4.11.3
- pyqode.core: 2.6.2
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment] 2015-05-25 12:30
This works for me: http://recordit.co/dBOzx18P9A

I am using PyQt5 on Windows 7 , not sure if that makes a difference...

**Comment by GitMensch** [comment] 2015-05-25 12:41
Looks nice, doesn't work for me. Can I simply uninstall PyQT4 and OCIDE will work after installing PyQT5?

**Comment by ColinDuquesnoy** [comment] 2015-05-25 12:44
Yes it that should work.

**Comment by GitMensch** [comment] 2015-05-25 12:55
I may should have been more specific: the Logs widget isn't restored even if it was viewed before restart (positions work, checked with PyQT5)

**Comment by ColinDuquesnoy** [comment] 2015-05-25 13:02
This is by design, the log widget (and the offset calculator) are hidden on startup. They are shown automatically when needed (i.e. when you hit compile/run)

**Comment by ColinDuquesnoy** [comment] 2015-05-25 13:21
Closing this since it is by design. Comment if you want me to reopen and discuss an alternative design

**Closed by ColinDuquesnoy** 2015-05-25 13:21 UTC
Labels: Invalid
