### ISSUE TITLE
[Bug] [Unhandled exception] ZeroDivisionError

### ISSUE THREAD

**Issue by lokedhs** [OpenCobolIDE/OpenCobolIDE#223] opened 2015-10-14 09:49 UTC
## Steps to reproduce

In the default "hello world" program, go to the end of line 20 (the working-storage section) and press return.

## Traceback

```
  File "/usr/lib/python3.5/site-packages/pyqode/cobol/modes/indenter.py", line 132, in indent
    self.min_column) % tab_len)

ZeroDivisionError: integer division or modulo by zero
```

## System information

- Operating System: Linux (arch  )
- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 2.0.0
- Python: 3.5.0 (64bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment] 2015-10-14 16:23
Thank you for reporting!

But I cannot reproduce the issue, at least not the way you describe. The only way I've found to reproduce this bug is by setting the indentation widthto 0 in the editor preferences (which is of course a bug that should be fixed).

**Closed** 2015-10-20 19:22 UTC
Labels: Bug, pyqode
