### ISSUE TITLE
[Bug] Some thoughts about the new report bug tool (see last comments)

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#253] opened 2015-11-03 07:24 UTC
Recognized after passing the log content in the Description. If it's too long (together with the version information) you see the truncation and the missing title.

This was the url passed to the browser (a length of 1850 bytes in total):

``https://github.com/OpenCobolIDE/OpenCobolIDE/issues/new?body=Works+fine+if+done+in+command+line...%0A%0AVerbose+log%3A%0A%0A~~~~~%0AINFO%3A%3Aopen_cobol_ide%3A%3Aversion%3A+4.7.dev58%0AINFO%3A%3Aopen_cobol_ide%3A%3Asys.stdout.encoding%3A+cp1252%0AINFO%3A%3Aopen_cobol_ide%3A%3Asys.getfilesystemencoding%3A+mbcs%0AINFO%3A%3Aopen_cobol_ide%3A%3Alocale.getpreferredencoding%3A+cp1252%0AINFO%3A%3Aopen_cobol_ide%3A%3Akernel32.GetACP%3A+cp1252%0ADEBUG%3A%3Aopen_cobol_ide.controllers.view%3A%3Ashowing+page+<Page.HOME%3A+0>%0ADEBUG%3A%3Aopen_cobol_ide.compilers%3A%3Acheck+compiler%0ADEBUG%3A%3Aopen_cobol_ide.msvc%3A%3Aquerying+vcvarsall%3A+"C%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\VC\vcvarsall.bat"+x86+set%0ADEBUG%3A%3Aopen_cobol_ide.compilers%3A%3APATH%3DD%3A\Entwicklung\gnu-cobol-2.0\bin%3BD%3A\Entwicklung\gnu-cobol-2.0\lib%3BC%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\VSTSDB\Deploy%3BC%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\Common7\IDE\%3BC%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\VC\BIN%3BC%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\Common7\Tools%3BC%3A\Windows\Microsoft.NET\Framework\v4.0.30319%3BC%3A\Windows\Microsoft.NET\Framework\v3.5%3BC%3A\Program+Files+(x86)\Microsoft+Visual+Studio+10.0\VC\VCPackages%3BC%3A\Program+Files+(x86)\Microsoft+SDKs\Windows\v7.0A\bin\NETFX+4.0+Tools%3BC%3A\Program+Files+(x86)\Microsoft+SDKs\Windows\v7.0A\bin%3BC%3A\ProgramData\Oracle\Java\javapath%3BC%3A\Windows\system32%3BC%3A\Windows%3BC%3A\Windows\System32\Wbem%3BC%3A\Program+Files+(x86)\Microsoft+SQL+Server\100\Tools\Binn\%3BC%3A\Program+Files\Microsoft+SQL+Server\100\Tools\Binn\%3BC%3A\Program+Files\Microsoft+SQL+Server\100\DTS\Binn\%3BC%3A\Program+Files+(x86)\Microsoft+SQL+Server\110\Tools\Binn\%3BC%3A\Program+Files\Microsoft+SQL+Server\110\Tools\Binn\%3BC%3A\Windows\System32\Windo``

According to http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers the length should be < 2000 characters (with a simple test I just got GitHub produce ``414 Request-URI Too Large`` ;-)

Therefore we should limit the content in the issue description. Maybe to 1200 characters (as different characters are expanded to multiple bytes)?

## System information

- OpenCobolIDE: 4.7.dev58
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by GitMensch** [comment] 2015-11-05 06:43
Implementing #132 would be a workaround. Therefore maybe not limit the output directly but depending on the way it is transmitted.

**Comment by GitMensch** [comment] 2016-01-15 18:54
Not sure if I should open a new bug "important information is missing in bug report"... The only thing that should be limited is text text entered by the user, the system information should always be in the text sent. So I'd suggest something like

~~~~~
if data['body'].length >= MAX_BODY_LENGTH
   data['body'][MAX_BODY_LENGTH - self.get_system_infos().length - 22] = '##OUTPUT STRIPPED##\n' + self.get_system_infos().
   MsgBox('text is stripped, please add the full text manually'),
   description.SaveToTextfileViaDlg
~~~~~

As addtion (Not sure if it's possible but this would solve the issue completely): can you add a text file upload like it's possible via browser? If yes then store the file automatically and upload it.

Your thoughts?

**Comment by GitMensch** [comment] 2016-01-15 19:01
Not sure if this works (not checked) but if it works by mailto then the app could check if the length is too big and warn to send it by mail otherwise (not sure what limit has to be taken into account that way).
If it works, then saving the file and using `&attachment=completedesc.txt` could be a workaround, too.

**Comment by ColinDuquesnoy** [comment] 2016-01-16 10:15
Another option might be to use the [github API](https://developer.github.com/v3/issues/). You would need to supply your github credentials to create the issue (credentials could be remembered using a [keyring](https://pypi.python.org/pypi/keyring)).

**Comment by ColinDuquesnoy** [comment] 2016-01-17 11:39
Using the github API seems to solve the problem (no more URI too large error). Tested on a temporary repo by sending the whole log file of the application after several compilations (which used to trigger the URI too large error).

The application log will now be automatically included (see #272).

User can choose whether they want their credentials to be remembered or not.

**Comment by GitMensch** [comment] 2016-01-28 20:30
I really like the new reporting module!

"Save credentials" don't work for me: they seem to be saved (there's no login box after the first login) but I get "Invalid credentials" message. Rechecked: the Box comes up the next time (which is good) but the valid credentials (which worked on the first test) are not accepted. Any idea what's going on?

A small additional bug: If you abort the GitHub login you get the message

~~~~
---------------------------
Login to github failed
---------------------------
Failed to create github issue, invalid credentials (error 401)
---------------------------
OK   
---------------------------
~~~~

I'd only expect this message to come (or to me more clear: the login attempt to be done) if I press "Sign In" (which is quite a huge "monster button" ;-)

Some other minor issues:
* The "Sign In" button is enabled by default and only gets disabled if one starts to type.
* If you enter invalid credentials, enable "Remember me" and sign in no credentials are stored (likely the same when there are other problems like connection) - I'd expect the credentials to be stored before the actual login.
* The generation of the additional text has two empty lines after `## System information`, but only one after `## Application log` (Should be the same, I personally think one line is enough).
* If OCIDE doesn't "know" that the GitHub ticket was send the "Report a bug" dialogue stays open. This is good. But as OCIDE cannot know if the mail actually was sent I'd suggest to leave it open if "Send email" was used (it is currently closed).
* The dialogue and the menu entry has the caption "Report a bug" which sounds like "we expect you to find a lot of bugs here". Can I suggest something along "Create an issue (Report a Bug/Suggest an Enhancement)" - it's too long, I know - this could be recycled as menu tooltip ;-) ?

**Comment by ColinDuquesnoy** [comment] 2016-01-28 20:47
> "Save credentials" don't work for me: they seem to be saved (there's no login box after the first login) but I get "Invalid credentials" message. Rechecked: the Box comes up the next time (which is good) but the valid credentials (which worked on the first test) are not accepted. Any idea what's going on?

I haven't tested it with the frozen application. I guess there is something wrong with the keyring backends. I'll have a look.

> The dialogue and the menu entry has the caption "Report a bug" which sounds like "we expect you to find a lot of bugs here". Can I suggest something along "Create an issue (Report a Bug/Suggest an Enhancement)" - it's too long, I know - this could be recycled as menu tooltip ;-) ?

Interesting. Not sure if "create an issue" sounds better though... Google chrome has the "Report an issue..." action in the help menu.

**Comment by GitMensch** [comment] 2016-01-28 20:55
> Interesting. Not sure if "create an issue" sounds better though... Google chrome has the "Report an issue..." action in the help menu.

I've just checked Firefox: "Send Feedback..." leading you to https://input.mozilla.org/de/feedback/firefox/43.0.4/ "Does the product make you happy" :-)

It's likely a good idea to ask not-techs first about a possible nice label before thinking too much about this as a programmer.

**Comment by ColinDuquesnoy** [comment] 2016-01-28 21:18
> It's likely a good idea to ask not-techs first about a possible nice label before thinking too much about this as a programmer.

You're probably right. I'll ask my girlfriend (she is the artist who made the ocide/hackedit icons).

**Comment by ColinDuquesnoy** [comment] 2016-01-30 15:02
There was really something wrong. I can reproduce the issue if I clear my keyring on Linux. I'll recheck everything works fine on windows with the frozen version.

I will use "Report an issue..." for the action's text and "Create an issue (Report a Bug/Suggest an Enhancement)" for the action's tooltip. "Issue" sounds less scary than "bug".

**Comment by ColinDuquesnoy** [comment] 2016-01-30 16:50
All those issues should be fixed. v4.7.1 has been uploaded.

**Comment by GitMensch** [comment] 2016-01-30 20:32
Looks good, despite of 1 issue:
If you use wrong credentials and check "remember me" you'll always get "check the log" and don't get the chance to enter correct credentials.

Just two additional thoughts:

* for "Send email" you may want to add the application name as prefix for the ticket, leading to [HackEdit][Enhancement] / [OpenCobolIDE][Bug]
* the shortcuts in this dialogue are a little be strange (did not checked before): Report a bug is "t" (I'd have expected "b"), Suggest an enhancement is "g" (expected "e"), the others don't have shortcuts (would expect title->t, description->d, github->g, email->e or m)

**Comment by GitMensch** [comment] 2016-01-30 20:34
The log output is:

~~~~~
ERROR::17984::open_cobol_ide.view.dialogs.report_bug::failed to send bug report
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\github.py", line 166, in _http
  File "C:\Python34\lib\urllib\request.py", line 469, in open
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
  File "C:\Python34\lib\urllib\request.py", line 507, in error
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\view\dialogs\report_bug.py", line 85, in submit
  File "C:\Python34\lib\site-packages\github.py", line 203, in __call__
  File "C:\Python34\lib\site-packages\github.py", line 178, in _http
github.ApiError: https://api.github.com/repos/OpenCobolIDE/OpenCobolIDE/issues
~~~~~

**Comment by ColinDuquesnoy** [comment] 2016-01-31 09:58
> If you use wrong credentials and check "remember me" you'll always get "check the log" and don't get the chance to enter correct credentials.

Well, the problem here is that the HttpError is masked by a github.ApiError, I can't make the distinction between a http error 401 and other errors. I'll look for a solution when working on the HE implementation and will backport it later to ocide (I'd like to wait a bit before making a new ocide release).

> for "Send email" you may want to add the application name as prefix for the ticket, leading to [HackEdit][Enhancement] / [OpenCobolIDE][Bug]

Sounds good.

> the shortcuts in this dialogue are a little be strange (did not checked before): Report a bug is "t" (I'd have expected "b"), Suggest an enhancement is "g" (expected "e"), the others don't have shortcuts (would expect title->t, description->d, github->g, email->e or m)

That's because they've been set automatically by Qt (I never use mnemonics so I always forget to check them^^)

**Closed** 2016-02-09 17:27 UTC
Labels: Bug

**Comment by ColinDuquesnoy** [comment] 2016-02-09 17:29
I've moved the bug report tool to an [external package](https://github.com/ColinDuquesnoy/QCrash), now the implementation is really shared with hackedit :)

I think I've solved the last issues remaining...

**Comment by GitMensch** [comment] 2016-02-10 17:18
Much better. Worked without adding a manual `pip3 install`.
Just two issues:

* new one: there is no separation between Bug and Enhancement, therefore the log/system environment gets uploaded every time (*could* be by design)
* there is no possibility to check the data which gets uploaded - this may be conflicting, especially in business environments

**Comment by ColinDuquesnoy** [comment] 2016-02-10 18:26
>  there is no separation between Bug and Enhancement, therefore the log/system environment gets uploaded every time (could be by design)

Yes by design. The distinction between an enhancement and bug is left to the maintainer (both are issues for the maintainer). How about adding two additional checkbox: "include system information" and "include application log".

> here is no possibility to check the data which gets uploaded - this may be conflicting, especially in business environments

I see. How about adding a "review" dialog where you can edit the final bug report? This dialog would show up when you click on a submit button (but maybe not for an email since you can edit it in your mail client anyway).

**Comment by GitMensch** [comment] 2016-02-10 19:07
> I see. How about adding a "review" dialog where you can edit the final bug report? This dialog would show up when you click on a submit button (but maybe not for an email since you can edit it in your mail client anyway).

Perfect solution.
