### ISSUE TITLE
OCIDE is unresponsive for > 20 seconds at startup

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#293] opened 2016-02-25 09:03 UTC
### Description

Steps to reproduce:

1 Start OCIDE
--> the welcome window is opened quite fast

2 Click anywhere (I've used "about OCIDE")
--> OCIDE is unresponsive for > 20 seconds

I don't know what OCIDE is doing (using 12-25% CPU on a dual-core --> 25-50% on one core) in this time and it isn't clear for me from the logs. But if this is necessary it should be done in a thread enabling the IDE to stay responsive.

BTW: For making sure neither the compiler startup nor the vcvars startup "eats" the time I've unchecked the PATH setting in compiler preferences and invalidated the vcvars - path (did not want to remove it as I'd have to find the full path again - a checkbox here like for the other entries would be nice)

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.2
- GnuCOBOL: 
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

### Application log

```
09:56:14:356::INFO::4892::open_cobol_ide::version: 4.7.2
09:56:14:695::DEBUG::4892::open_cobol_ide.controllers.view::showing page <Page.HOME: 0>
09:56:14:721::DEBUG::4892::open_cobol_ide.compilers::check compiler
09:56:14:723::DEBUG::4892::open_cobol_ide.msvc::querying vcvarsall
09:56:14:723::DEBUG::4892::open_cobol_ide.msvc::querying vcvarsall: "_C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86 set
09:56:14:725::ERROR::4892::open_cobol_ide.msvc::exception while querying vcvarsall
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\msvc.py", line 59, in query_vcvarsall
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
09:56:14:725::DEBUG::4892::open_cobol_ide.msvc::vcenv: {}
09:56:14:726::ERROR::4892::open_cobol_ide.msvc::failed to read key from vcvarsall
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\msvc.py", line 38, in get_vc_vars
KeyError: 'lib'
09:56:14:726::ERROR::4892::open_cobol_ide.msvc::failed to read key from vcvarsall
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\msvc.py", line 38, in get_vc_vars
KeyError: 'libpath'
09:56:14:727::ERROR::4892::open_cobol_ide.msvc::failed to read key from vcvarsall
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\msvc.py", line 38, in get_vc_vars
KeyError: 'include'
09:56:14:727::ERROR::4892::open_cobol_ide.msvc::failed to read key from vcvarsall
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\msvc.py", line 38, in get_vc_vars
KeyError: 'path'
09:56:14:727::DEBUG::4892::open_cobol_ide.compilers::PATH=
09:56:14:730::DEBUG::4892::open_cobol_ide.compilers::command: cobc.exe -x C:\Users\Simon\AppData\Local\Temp\test.cbl
09:56:14:731::DEBUG::4892::open_cobol_ide.compilers::working directory: C:\Users\Simon\AppData\Local\Temp
09:56:14:731::DEBUG::4892::open_cobol_ide.compilers::environment: [-removed from report-]
09:56:14:732::DEBUG::4892::open_cobol_ide.compilers::output: ''
09:56:14:733::DEBUG::4892::open_cobol_ide.compilers::exit code: 0
09:56:14:734::DEBUG::4892::open_cobol_ide.compilers::PATH=
09:56:14:737::DEBUG::4892::open_cobol_ide.compilers::command: cobc.exe C:\Users\Simon\AppData\Local\Temp\test.cbl
09:56:14:737::DEBUG::4892::open_cobol_ide.compilers::working directory: C:\Users\Simon\AppData\Local\Temp
09:56:14:737::DEBUG::4892::open_cobol_ide.compilers::environment: [-removed from report-]
09:56:14:738::DEBUG::4892::open_cobol_ide.compilers::output: ''
09:56:14:738::DEBUG::4892::open_cobol_ide.compilers::exit code: 0
09:56:14:739::INFO::4892::open_cobol_ide.compilers::GnuCOBOL compiler check: success
09:56:14:739::INFO::4892::open_cobol_ide.compilers::Executable extension: .exe
09:56:14:740::INFO::4892::open_cobol_ide.compilers::Module extension: .dll
09:56:14:740::DEBUG::4892::open_cobol_ide.compilers::getting cobc version: cobc.exe --version
09:56:14:741::DEBUG::4892::open_cobol_ide.compilers::PATH=
09:56:14:744::DEBUG::4892::open_cobol_ide.compilers::command: cobc.exe --version
09:56:14:744::DEBUG::4892::open_cobol_ide.compilers::working directory: 
09:56:14:744::DEBUG::4892::open_cobol_ide.compilers::environment: [-removed from report-]
09:56:14:745::DEBUG::4892::open_cobol_ide.compilers::output: ''
09:56:14:746::DEBUG::4892::open_cobol_ide.compilers::exit code: 0
09:56:14:746::INFO::4892::open_cobol_ide.app::GnuCOBOL version: 
09:56:36:671::DEBUG::4892::open_cobol_ide.compilers::getting cobc version: cobc.exe --version
09:56:36:672::DEBUG::4892::open_cobol_ide.compilers::PATH=
09:56:36:675::DEBUG::4892::open_cobol_ide.compilers::command: cobc.exe --version
09:56:36:675::DEBUG::4892::open_cobol_ide.compilers::working directory: 
09:56:36:676::DEBUG::4892::open_cobol_ide.compilers::environment: [-removed from report-]
09:56:36:677::DEBUG::4892::open_cobol_ide.compilers::output: ''
09:56:36:677::DEBUG::4892::open_cobol_ide.compilers::exit code: 0
```

**Comment by GitMensch** [comment] 2016-02-25 09:07
If you cannot reproduce this at all I can run OCIDE again checking what it is doing by ProcessExplorer/ProcDump/ProcMonitor if this helps.

**Comment by ColinDuquesnoy** [comment] 2016-02-25 09:33
I think I know what might happen: if the log file is very big, it will take sometime to display it in QPlainTextEdit. This operation is a gui operation that cannot be done in a background thread... A possible solution would be to use [QPlainTextEdit::setMaximumBlockCount](http://doc.qt.io/qt-5/qplaintextedit.html#maximumBlockCount-prop).

**Comment by GitMensch** [comment] 2016-02-25 12:28
This isn't the problem here - it doesn't matter what is pressed : the welcome screen comes up directly, as soon as it is visible OCIDE is unresponsive for ~ 20 seconds.

**Comment by ColinDuquesnoy** [comment] 2016-02-25 17:00
> This isn't the problem here - it doesn't matter what is pressed : the welcome screen comes up directly, as soon as it is visible OCIDE is unresponsive for ~ 20 seconds (same if "About" is not clicked - and the log file above was the complete content)

Ok. Does it goes away if you correct the vcvarsall path?

**Comment by ColinDuquesnoy** [comment] 2016-02-25 18:34
> This isn't the problem here

Maybe but I fixed it anyway (it will only show the last 1000 lines).

> the welcome screen comes up directly, as soon as it is visible OCIDE is unresponsive for ~ 20 seconds (same if "About" is not clicked - and the log file above was the complete content)

I have no idea what is happening. I cannot reproduce this at all. I've checked the code and debugged it a bit: OCIDE does nothing once the welcome screen has been shown. All compiler checks are done before showing the window and there is no pyqode backend running, just the Qt event loop...

I'll need more information.

**Comment by GitMensch** [comment] 2016-03-03 12:57
I rechecked with ProcExp and I know what's going on: in the time where OCIDE is unresponsive it opens different file handles to a network folder. Rechecked more via registry: it is neither `recent_files\last` (which I've thought before) nor the setting `lastUsedPath`. But it is the setting `lock_fs_path`.

What is `lock_fs_path` for?

Suggestion:
* Whatever you do with it: do it in a parallel thread not blocking the application.
* Make sure to log whatever is done (you may do this already and this is only a matter of setting the correct debug levels like you said in #287 [shouldn't this have an own issue for tracking?]).
* Force the `lock_fs_path` to the same path as the log file, if possible.

**Comment by ColinDuquesnoy** [comment] 2016-03-03 17:12
> Make sure to log whatever is done (you may do this already and this is only a matter of setting the correct debug levels like you said in #287 [shouldn't this have an own issue for tracking?]).

Yes, same issue, tracked in #295.

> same path as the log file, if possible.

Not sure I understand what you mean here. Which path are you referring to?

> What is lock_fs_path for?

``lock_fs_path`` is the setting that stores the path you locked in the file system tree view (part of what you asked in #291 is already implemented). That path is restored when you start the IDE, that's what slows down OCIDE. Unfortunately there is nothing I can do, the file system model is already filled in a background thread but threading in python is not always helpful due to the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock).

Closing as won't fix.

**Comment by GitMensch** [comment] 2016-03-03 19:13
OK, I see what `lock_fs_path` is for. Forget the suggestion about the change of the path.

> That path is restored when you start the IDE, that's what slows down OCIDE. Unfortunately there is nothing I can do, the file system model is already filled in a background thread but threading in python is not always helpful due to the GIL.

Hm, I'm unsure about this, there must be a solution...

Quoting from https://wiki.python.org/moin/GlobalInterpreterLock

> The GIL is controversial because it prevents multithreaded CPython programs from taking full advantage of multiprocessor systems in certain situations. *Note that potentially blocking or long-running operations, such as I/O [...] happen outside the GIL*. Therefore it is only in multithreaded programs that spend a lot of time inside the GIL, interpreting CPython bytecode, that the GIL becomes a bottleneck.

I guess OCIDE could restore it when the file system view gets actually shown (=activated the first time), if it isn't used in the complete session then this issue will never arise. And it's quite clear what the problem is and the user has the option to directly change it afterwards.
What do you think about delaying the restore to this event?

**Comment by ColinDuquesnoy** [comment] 2016-03-03 19:20
> I guess OCIDE could restore it when the file system view gets actually shown (=activated the first time), if it isn't used in the complete session then this issue will never arise. And it's quite clear what the problem is and the user has the option to directly change it afterwards.
What do you think about delaying the restore to this event?

AFAIK, the only way to release the GIL is by writing a c extension module, not something I plan to do.

**Comment by ColinDuquesnoy** [comment] 2016-03-03 19:45
> What do you think about delaying the restore to this event?

I took some time to understand what you meant. Yes, once #291 has been implemented I could delay the initialisation of the tree view.

**Comment by GitMensch** [comment] 2016-04-10 13:33
Yay, 291 is closed ;-)

**Comment by ColinDuquesnoy** [comment] 2016-04-10 13:35
Yes but I still need to delay the initialisation of the treeview. Should be done soon ;-)

**Comment by ColinDuquesnoy** [comment] 2016-04-10 14:06
Tested on Linux, the treeview won't be initialized until it is shown.

**Closed** 2016-04-10 14:06 UTC
Labels: performances, pyqode

**Comment by GitMensch** [comment] 2016-04-11 07:50
Confirmed as working :+1:
