### ISSUE TITLE
SQLCODE -4903 in OpenCOBOL IDE - Windows 8.1 / DB2 Express-C / GnuCOBOL

### ISSUE THREAD

**Issue by askadian** [OpenCobolIDE/OpenCobolIDE#329] opened 2016-04-29 12:56 UTC
I have a GnuCOBOL application compiled and executed by OpenCOBOL IDE on Windows 8.1. This application/program is FETCHing data from DB2 Express C, which is also installed on same machine(localhost:50000). Precompile is fine and BIND creates a package in DB2. When I execute this program using OpenCOBOL IDE, I get SQLCODE -4903.

OpenCOBOL IDE Forum and developers say it is related to DB2 Express C.

```
F:\COBOL\bin\TEST0002.exe 
CONNECT :)+0000000000+1ÿ1208ÿAKADIAN ÿSAMPLEÿQDB2/NT64ÿ29703ÿ29703ÿ0ÿ1252ÿ0ÿ                
SQLCODE: -0000004903
SQLCAID: SQLCA   
SQLCABC: +0000000136
SQLERRML: +00028
SQLERRMC: runtime_pidÿsqlastrt_trusted                                          
SQLERRP: SQLASTRT
SQLSTATE: 42611
SQLWARN:            
Hello world: 0 -->THIS SHOULD BE 1 IF SQL WORKED :)  
--- error report ---
ERROR occurred :                                                                                 
SQLCODE : -0000004903
SQL4903N  The length of parameter "runtime_pid" of function "sqlastrt_trusted" 
is not valid.  SQLSTATE=42611

SQLSTATE 42611: The column, argument, parameter, or global variable definition 
is invalid.
--- end error report ---

Process finished with exit code 94
```

What is exit code 94? How can we resolve this?
same issue on [sourceforge](https://sourceforge.net/p/open-cobol/discussion/cobol/thread/1956431c/) and [idug](http://www.idug.org/p/fo/st/thread=46001&post=175776&posted=1#p175776)

**Comment by askadian** [comment] 2016-05-10 18:58
Need to find out if this is related to IDE, or corresponding GnuCOBOL or DB2? Any help is appreciated.

**Comment by ColinDuquesnoy** [comment] 2016-05-11 07:51
> Need to find out if this is related to IDE

That is easy, just compile the program from command line. If it works from command line then there is a bug in OCIDE, report back and I'll investigate. If it does not work from command line than the issue is somewhere else, in that case please close this issue.

**Comment by GitMensch** [comment] 2016-05-30 10:27
@askadian According to [http://stackoverflow.com/questions/36607472/how-to-resolve-sqlcode-805-in-db2-express-c-windows-8-1-gnucobol-opencobol-i] you have solved at least the 805 error, is the same true for the 4903 error (can we close this issue)? If yes: what was the actual fix/change?

**Comment by askadian** [comment] 2016-05-31 19:13
-805 got resolved but I was not able resolve the -4903. There were suggestions to build my own 64 bit GnuCOBOL and use the same in OpenCOBOL IDE. [https://sourceforge.net/p/open-cobol/discussion/cobol/thread/1956431c/?limit=250#de9d](url)

**Closed** 2016-11-11 12:11 UTC
