### ISSUE TITLE
Bug at startup

### ISSUE THREAD

**Issue by datt-neelabh** [OpenCobolIDE/OpenCobolIDE#266] opened 2015-11-29 09:32 UTC
![errorwhenstartingtheprogram](https://cloud.githubusercontent.com/assets/15855526/11456274/62233de2-96aa-11e5-9e49-69ef204b377f.JPG)
The COBOL ide is not starting up. This is the error message I am getting at the startup.
(Please see the file attached). My operating system is Windows XP Service Pack 3 x86.

**Comment by ColinDuquesnoy** [comment] 2015-11-29 10:13
Hello,

Thank you for reporting! What version of OCIDE are you using? Can you try with the latest preview build? https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview4

This looks like a bug in the mimetypes module which is part of the python standard library. It might have been fixed in the latest python3 version for windows which I am using in the latest preview build...

**Comment by datt-neelabh** [comment] 2015-11-30 12:09
The version of OpenCOBOLIDE I was using was 4.6.6. I have downloaded the new version 4.7 and have tested it. It is too giving the same kind of error at startup. Please help.
![problem_new_4 7](https://cloud.githubusercontent.com/assets/15855526/11470853/1c460394-9787-11e5-82df-1fc1c75fb65b.JPG)

**Comment by ColinDuquesnoy** [comment] 2015-11-30 16:29
Sigh... I hoped it would have been fixed with the new version of Python.

Unfortunately I have no idea why this is happening. I can't reproduce that bug and I am pretty sure I cannot fix it from the OCIDE/pyqode code. It seems to be a defect on your system.

There a few things you might want to try:
- you said it was working before, do you remember what you changed? If yes try to undo that change (I know it's easier said than done).
- since this seems to be registry related error, have you tried to fix potential registry errors (e.g. using ccleaner or any other similar tool)
- if after cleaning the registry you still can't make it work then your last resort is to install the IDE in development mode (install python3, pyqt5 and a python IDE (I'd suggest to use pycharm)) and debug the issue yourself.

For now, I am going to close this issue because I feel like I cannot fix it in OCIDE or pyqode. Comment here if you make any interesting discoveries while debugging.

**Closed by ColinDuquesnoy** 2015-11-30 16:29 UTC

**Comment by GitMensch** [comment] 2015-12-04 07:43
Just one thing I've recognized: this is a Windows XP system (= not any longer supported). I guess that's the reason Colin can't reproduce the issue.
