### ISSUE TITLE
File encoding issue

### ISSUE THREAD

**Issue by zebuscat** [OpenCobolIDE/OpenCobolIDE#96] opened 2015-01-11 00:47 UTC
Hi - trying to edit animator.cbl v2.0  (TP-Cobol-Debugger project) - source has 2.358 lines - OpenCobolIDE 4.2 will not open the file under MacOS X 10.10.01.

Regards
Dirk

### System information
* Operating System: Mac OS X 10.10.01
* OpenCobolIDE Version: 4.2

**Comment by ColinDuquesnoy** [comment] 2015-01-11 11:49
Hello, 

Thanks for reporting the issue!

I've download that file: http://sourceforge.net/p/tp-cobol-debugg/code/HEAD/tree/trunk/animator.cbl

And It's working like a charm for me  (OpenCobolIDE v4.3 on OSX 10.10). See:
![screen shot 2015-01-11 at 12 49 16](https://cloud.githubusercontent.com/assets/1681217/5695096/4941414c-9990-11e4-828b-c23cec2747fe.png)


(it might take some time for loading the file, this is limitation of the qt text api).

May I ask you to try with the latest version and see if it works for you?

**Comment by ColinDuquesnoy** [comment] 2015-01-11 12:07
I've just tried with v4.2 and it's also working fine for me.

So I guess the issue is very specific to the file you're tying to open, maybe an encoding issue. Large files are working with the IDE but it might be a bit slow to load very large files (more than 100 K lines).

Could you send me a link to download the exact file you're trying to edit?

**Comment by zebuscat** [comment] 2015-01-11 13:01
Hi Colin
I've loaded the zipped package from here : 
http://sourceforge.net/projects/tp-cobol-debugg/files/tp-cobol-debugger/0.2.0/tp-cobol-debugger-2.00-08-10-2014.zip/download

After extraxt I did some CHMOD to correct the file attributes .
MiniYosemite:animator 2.00 dirk$ ls -lisa *.cbl
13049548  64 -rw-r--r--@ 1 dirk  staff  32629  8 Apr  2012 analyzer.cbl
13049549  88 -rw-r--r--@ 1 dirk  staff  42126 18 Okt 22:58 animate.cbl
13049551 160 -rw-r--r--@ 1 dirk  staff  81833 18 Okt 23:11 animator.cbl
13049555  72 -rw-r--r--@ 1 dirk  staff  33724 19 Okt 07:44 animdata.cbl
13049556  24 -rw-r--r--@ 1 dirk  staff   8398 19 Okt 07:44 animfind.cbl
13049557  40 -rw-r--r--@ 1 dirk  staff  18254 19 Okt 07:45 animloca.cbl
13049558  16 -rw-r--r--@ 1 dirk  staff   6167 19 Okt 07:45 animview.cbl
13049659  16 -rw-r--r--@ 1 dirk  staff   6778 26 Jul  2011 test.cbl

v4.2 will open all  .cbl source files , except animator.cbl ?

Dirk

**Comment by zebuscat** [comment] 2015-01-11 13:05
Using a TextEditor e.g TextWrangler will open animator.cbl - no issue.

**Comment by ColinDuquesnoy** [comment] 2015-01-11 13:23
Thanks! This was helpful and the bug is already fixed in v4.3.

This is an encoding issue. `animator.cbl` is encoded using `cp1252` and all the other files are encoded using ùtf-8`. OpenCobolIDE does not detect encoding automatically. It first tries to load the file using the native encoding (usually UTF8 on OS X) and if that fails, it shows a panel at the top of the editor to let you choose the correct encoding. There was a regression in v4.2 where that panel would not show up.

So you have to download v4.3 () and follow the next steps to configure the editor to open ``animator.cbl``:

1)  this is what you will see the first time you open animator.cbl: 

![screen shot 2015-01-11 at 14 05 33](https://cloud.githubusercontent.com/assets/1681217/5695319/485108d8-999c-11e4-9ff3-44ff7c0fca53.png)

2) click in the Character encoding combo box and select ``Add or remove``

![screen shot 2015-01-11 at 14 18 15](https://cloud.githubusercontent.com/assets/1681217/5695323/ca205bb6-999c-11e4-84a6-31c48bd1af43.png)

3) Select ``Windows-1252`` from the available encoding list, add it to your preferred encodings and click OK.

![screen shot 2015-01-11 at 14 05 49](https://cloud.githubusercontent.com/assets/1681217/5695328/dc3da3ee-999c-11e4-9b0d-79cda7ee247f.png)

4) Select ``windows-1252 (western)``in the character encoding combo box and click on ``Retry``

![screen shot 2015-01-11 at 14 05 56](https://cloud.githubusercontent.com/assets/1681217/5695341/1ce35c18-999d-11e4-81a1-e010ccf69ef1.png)

The file should now load properly and the IDE will remember to use cp1252 whenever you open that file.

**Comment by zebuscat** [comment] 2015-01-11 13:23
I have now installed OpenCobolIDE v4.3.
The following errmsg shows up when opening animator.cbl:
![animator cbl open](https://cloud.githubusercontent.com/assets/10481353/5695342/206c7ab8-999d-11e4-8ad2-dee075b6f2e2.jpg)

So there seems to be a encoding issue

**Comment by zebuscat** [comment] 2015-01-11 13:24
Done - thank you for your support !!

;-)

**Closed** 2015-01-11 13:27 UTC
Labels: Bug

**Comment by ColinDuquesnoy** [comment] 2015-01-11 14:02
> Done - thank you for your support !!
;-)

You're welcome! Thanks to your report, there is a new entry in the [FAQ](http://opencobolide.readthedocs.org/en/latest/faq.html#opencobolide-failed-to-open-a-file-due-to-an-encoding-issue-what-can-i-do) about file encoding issues.
