### ISSUE TITLE
something is missing in the installer

### ISSUE THREAD

**Issue by Naitsirc01** [OpenCobolIDE/OpenCobolIDE#415] opened 2017-04-15 15:51 UTC
Well, i was install the lastest version 4.7.6 and when i try to compile my "hello world" this show me: invalid argument line 1, i checked the compiler and works, but the error continuos, with this i decide unistall 4.7.6 and install previous version 4.7.4 this solved the problem, but when i run the first "hello world" this show a error something lib.... is missing, finally i have reinstalled the lastest version and works without problem.

That's my comment...

**Comment by GitMensch** [comment] 2017-04-24 09:46
Is this just a note or a bug report? What can you do to reproduce the error?
I assume you used the Windows installer, the main difference between 4.7.4 and 4.7.6 is that 4.7.6 ships with GnuCOBOL 2.0rc2 while all versions down to 4.6.2 ship GnuCOBOL 1.1 (and down from this shipping OpenCOBOL 1.1). The folders containing these Mingw packages have different names, therefore you may run into problems if you changed the default options - resetting the should have fixed the issue.

**Comment by Naitsirc01** [comment] 2017-04-24 19:53
Yes, i use Windows installer, i thinks is a bug report, taking into account the difference of the installers, this should explain why libcob-1.dll is missing.

For reproduce the error, i uninstall the version 4.7.4, reinstall 4.7.6 and this show me:

![error 4 7 6](https://cloud.githubusercontent.com/assets/27567231/25353965/7cc4ae42-2907-11e7-90c9-691ee985db7d.JPG)

![error](https://cloud.githubusercontent.com/assets/27567231/25354009/9ebe61e6-2907-11e7-9b97-e45cac9a1be2.JPG)

![4 7 6](https://cloud.githubusercontent.com/assets/27567231/25354016/a6361e00-2907-11e7-9a75-d614953e5c25.JPG)

reinstalling 4.7.4 and now trying to compile "hello world" of 4.7.6 :


![4 7 4 with first hello world](https://cloud.githubusercontent.com/assets/27567231/25354124/1c08d0b4-2908-11e7-9b2e-745354a71dac.JPG)

![4 7 4 with first hello world compiler](https://cloud.githubusercontent.com/assets/27567231/25354126/1fef41cc-2908-11e7-95ac-d2a68fb1242c.JPG)

This also happens if I try to compile a .cob file create by 4.7.4

![cob](https://cloud.githubusercontent.com/assets/27567231/25354783/b98470ee-290a-11e7-8e0e-16925cf3fff1.JPG)

now reinstall 4.7.6 and try to compile the hello world create by 4.7.4:

![4 7 6 libcob-1 dll](https://cloud.githubusercontent.com/assets/27567231/25355017/9de7d758-290b-11e7-91ef-0b3d2677b80a.JPG)

this say:
"The program can not start because libcob-1.dll is missing from the computer.
Try reinstalling the program to correct this problem."

![4 7 6 libcob](https://cloud.githubusercontent.com/assets/27567231/25355082/d2dfe856-290b-11e7-8663-627fefe02869.JPG)

**Comment by GitMensch** [comment] 2017-04-24 20:11
Thank you, now it is a bug report :-)

Please replace the first screen shot with testing the second sample "hello.cbl", not "hello world.cob" (which may not work depending on the version of GnuCOBOL you use and the way OCIDE passes the parameters.

Please add the following information:

What subfolders do you have in `%ProgramFiles%\OpenCobolIDE` in these installation steps? 
How do the compiler preferences (F2) look like?

**Comment by Naitsirc01** [comment] 2017-04-25 03:29
4.7.4:

C:\Program Files (x86)\OpenCobolIDE

Compiler preferences:

![compiler 4 7 4](https://cloud.githubusercontent.com/assets/27567231/25367696/c04d23f6-294d-11e7-80a3-b7eab67119fb.JPG)

4.7.6:

same C:\Program Files (x86)\OpenCobolIDE

same

![compiler preferences 4 7 6](https://cloud.githubusercontent.com/assets/27567231/25367745/1f99c7e2-294e-11e7-87ee-e2596e1df211.JPG)

**Comment by GitMensch** [comment] 2017-04-25 06:57
The workaround "Finally the solution I found was to install version 4.7.4 then install version 4.7.6 without uninstalling 4.7.4. By doing this, version 4.7.6 works without problems." may work, but it is wrong. I actually did install it the same way here and checking in the bin directory shows that libcob-1.dll belongs to the official GnuCOBOL 1.1 Mingw package (that was bundled up to 4.7.4) while libcob-4.dll belongs to the GnuCOBOL 2.0rc MinGW package that comes bundled with 4.7.6.

Therefore the question is "why is libcob-1.dll looked for", the only possible answer: you either compile with an old `cobc` (which I don't assume as the installer replaces the version in `C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin` (to check this open this path in command prompt and call `cobc --version`) or have an old `hello.exe` laying on your harddisk (check its time stamp after compilation, you can find the file in taskmanager: run it until you see the libcob-1.dll error message, leave it open, open taskmanager->details and open the properties of hello.exe - this tells you where it is, too - something you may want to verify in the process, too).

The issue how the installer should handle the in-place installation (upgrade) is already tracked in #394 which is in the next milestone and I've added some notes about it there.

**Comment by ColinDuquesnoy** [comment] 2017-04-29 15:51
Closing as a duplicate of #394, please continue the discussion there.

**Closed by ColinDuquesnoy** 2017-04-29 15:51 UTC
Labels: Bug, Duplicate, Packaging, Windows
